import os

# Get the directory of this file (inside static)
current_dir = os.path.dirname(os.path.abspath(__file__))
# Create a "themes" folder inside the static folder
output_dir = os.path.join(current_dir, "themes")
os.makedirs(output_dir, exist_ok=True)

# Define multiple themes (original plus extra 15 themes)
themes = {
    "dark": {
        "bg-primary": "#1e1e1e",
        "bg-secondary": "#252526",
        "bg-tertiary": "#333333",
        "bg-input": "#3c3c3c",
        "bg-hover": "#4a4a4a",
        "text-primary": "#d4d4d4",
        "text-secondary": "#cccccc",
        "text-placeholder": "#7a7a7a",
        "accent-primary": "#0e639c",
        "accent-secondary": "#4CAF50",
        "border-color": "#444444",
        "danger-color": "#f44336",
        "danger-hover-color": "#d32f2f",
        "modal-bg": "rgba(0, 0, 0, 0.7)",
        "modal-content-bg": "#2d2d2d",
        "scrollbar-thumb": "#555",
        "scrollbar-track": "#252526",
        "code-bg": "#272822"
    },
    "light": {
        "bg-primary": "#f5f5f5",
        "bg-secondary": "#ffffff",
        "bg-tertiary": "#eeeeee",
        "bg-input": "#e0e0e0",
        "bg-hover": "#e0e0e0",
        "text-primary": "#333333",
        "text-secondary": "#555555",
        "text-placeholder": "#999999",
        "accent-primary": "#007acc",
        "accent-secondary": "#4CAF50",
        "border-color": "#dddddd",
        "danger-color": "#e53935",
        "danger-hover-color": "#c62828",
        "modal-bg": "rgba(255, 255, 255, 0.7)",
        "modal-content-bg": "#ffffff",
        "scrollbar-thumb": "#aaa",
        "scrollbar-track": "#f5f5f5",
        "code-bg": "#f0f0f0"
    },
    "blue": {
        "bg-primary": "#E3F2FD",
        "bg-secondary": "#BBDEFB",
        "bg-tertiary": "#90CAF9",
        "bg-input": "#64B5F6",
        "bg-hover": "#42A5F5",
        "text-primary": "#0D47A1",
        "text-secondary": "#1976D2",
        "text-placeholder": "#64B5F6",
        "accent-primary": "#1565C0",
        "accent-secondary": "#1E88E5",
        "border-color": "#90CAF9",
        "danger-color": "#E53935",
        "danger-hover-color": "#C62828",
        "modal-bg": "rgba(0, 0, 0, 0.3)",
        "modal-content-bg": "#BBDEFB",
        "scrollbar-thumb": "#64B5F6",
        "scrollbar-track": "#E3F2FD",
        "code-bg": "#BBDEFB"
    },
    "red": {
        "bg-primary": "#330000",
        "bg-secondary": "#440000",
        "bg-tertiary": "#550000",
        "bg-input": "#660000",
        "bg-hover": "#770000",
        "text-primary": "#f5f5f5",
        "text-secondary": "#cccccc",
        "text-placeholder": "#999999",
        "accent-primary": "#ff4d4d",
        "accent-secondary": "#ff0000",
        "border-color": "#aa0000",
        "danger-color": "#ff6666",
        "danger-hover-color": "#ff3333",
        "modal-bg": "rgba(0, 0, 0, 0.7)",
        "modal-content-bg": "#660000",
        "scrollbar-thumb": "#aa0000",
        "scrollbar-track": "#440000",
        "code-bg": "#330000"
    },
    "green": {
        "bg-primary": "#003300",
        "bg-secondary": "#004400",
        "bg-tertiary": "#005500",
        "bg-input": "#006600",
        "bg-hover": "#007700",
        "text-primary": "#e0ffe0",
        "text-secondary": "#b3ffb3",
        "text-placeholder": "#80ff80",
        "accent-primary": "#00ff00",
        "accent-secondary": "#33cc33",
        "border-color": "#006600",
        "danger-color": "#ff6666",
        "danger-hover-color": "#ff3333",
        "modal-bg": "rgba(0, 0, 0, 0.7)",
        "modal-content-bg": "#004400",
        "scrollbar-thumb": "#007700",
        "scrollbar-track": "#003300",
        "code-bg": "#002200"
    },
    "purple": {
        "bg-primary": "#1a001a",
        "bg-secondary": "#2e002e",
        "bg-tertiary": "#450045",
        "bg-input": "#590059",
        "bg-hover": "#6d006d",
        "text-primary": "#e6e6ff",
        "text-secondary": "#ccccff",
        "text-placeholder": "#b3b3ff",
        "accent-primary": "#9933ff",
        "accent-secondary": "#8c1aff",
        "border-color": "#6600cc",
        "danger-color": "#ff6666",
        "danger-hover-color": "#ff3333",
        "modal-bg": "rgba(0, 0, 0, 0.7)",
        "modal-content-bg": "#2e002e",
        "scrollbar-thumb": "#450045",
        "scrollbar-track": "#2e002e",
        "code-bg": "#1a001a"
    },
    "orange": {
        "bg-primary": "#332600",
        "bg-secondary": "#4d3300",
        "bg-tertiary": "#664d00",
        "bg-input": "#806600",
        "bg-hover": "#997a00",
        "text-primary": "#fff2e6",
        "text-secondary": "#ffddb3",
        "text-placeholder": "#ffcc80",
        "accent-primary": "#ff8800",
        "accent-secondary": "#ff6600",
        "border-color": "#cc5200",
        "danger-color": "#ff8c66",
        "danger-hover-color": "#ff6633",
        "modal-bg": "rgba(0, 0, 0, 0.7)",
        "modal-content-bg": "#4d3300",
        "scrollbar-thumb": "#ff6600",
        "scrollbar-track": "#4d3300",
        "code-bg": "#332600"
    },
    "pink": {
        "bg-primary": "#331933",
        "bg-secondary": "#4d3350",
        "bg-tertiary": "#663366",
        "bg-input": "#803380",
        "bg-hover": "#993399",
        "text-primary": "#ffe6f2",
        "text-secondary": "#ffccd9",
        "text-placeholder": "#ffb3c0",
        "accent-primary": "#ff66cc",
        "accent-secondary": "#ff33aa",
        "border-color": "#cc3388",
        "danger-color": "#ff99cc",
        "danger-hover-color": "#ff66aa",
        "modal-bg": "rgba(0, 0, 0, 0.7)",
        "modal-content-bg": "#4d3350",
        "scrollbar-thumb": "#ff33aa",
        "scrollbar-track": "#4d3350",
        "code-bg": "#331933"
    },
    "teal": {
        "bg-primary": "#003d3d",
        "bg-secondary": "#004f4f",
        "bg-tertiary": "#006060",
        "bg-input": "#007171",
        "bg-hover": "#008282",
        "text-primary": "#e0ffff",
        "text-secondary": "#b3ffff",
        "text-placeholder": "#80ffff",
        "accent-primary": "#00cccc",
        "accent-secondary": "#00b3b3",
        "border-color": "#006666",
        "danger-color": "#ff6666",
        "danger-hover-color": "#ff3333",
        "modal-bg": "rgba(0, 0, 0, 0.7)",
        "modal-content-bg": "#004f4f",
        "scrollbar-thumb": "#008282",
        "scrollbar-track": "#003d3d",
        "code-bg": "#002f2f"
    },
    "brown": {
        "bg-primary": "#3e2723",
        "bg-secondary": "#4e342e",
        "bg-tertiary": "#5d4037",
        "bg-input": "#6d4c41",
        "bg-hover": "#7e5e58",
        "text-primary": "#efebe9",
        "text-secondary": "#d7ccc8",
        "text-placeholder": "#bcaaa4",
        "accent-primary": "#795548",
        "accent-secondary": "#6d4c41",
        "border-color": "#5d4037",
        "danger-color": "#ff8a65",
        "danger-hover-color": "#ff7043",
        "modal-bg": "rgba(0, 0, 0, 0.7)",
        "modal-content-bg": "#4e342e",
        "scrollbar-thumb": "#7e5e58",
        "scrollbar-track": "#3e2723",
        "code-bg": "#3e2723"
    },
    "yellow": {
        "bg-primary": "#fffde7",
        "bg-secondary": "#fff9c4",
        "bg-tertiary": "#fff59d",
        "bg-input": "#fff176",
        "bg-hover": "#ffee58",
        "text-primary": "#212121",
        "text-secondary": "#424242",
        "text-placeholder": "#757575",
        "accent-primary": "#fdd835",
        "accent-secondary": "#fbc02d",
        "border-color": "#f9a825",
        "danger-color": "#e53935",
        "danger-hover-color": "#d32f2f",
        "modal-bg": "rgba(0, 0, 0, 0.7)",
        "modal-content-bg": "#fff9c4",
        "scrollbar-thumb": "#fdd835",
        "scrollbar-track": "#fffde7",
        "code-bg": "#fffde7"
    },
    "gray": {
        "bg-primary": "#eeeeee",
        "bg-secondary": "#e0e0e0",
        "bg-tertiary": "#cccccc",
        "bg-input": "#bdbdbd",
        "bg-hover": "#9e9e9e",
        "text-primary": "#424242",
        "text-secondary": "#616161",
        "text-placeholder": "#757575",
        "accent-primary": "#757575",
        "accent-secondary": "#616161",
        "border-color": "#bdbdbd",
        "danger-color": "#e53935",
        "danger-hover-color": "#d32f2f",
        "modal-bg": "rgba(0, 0, 0, 0.7)",
        "modal-content-bg": "#e0e0e0",
        "scrollbar-thumb": "#9e9e9e",
        "scrollbar-track": "#eeeeee",
        "code-bg": "#f5f5f5"
    },
    "cyber": {
        "bg-primary": "#0f0f0f",
        "bg-secondary": "#1a1a1a",
        "bg-tertiary": "#262626",
        "bg-input": "#333333",
        "bg-hover": "#404040",
        "text-primary": "#00ffea",
        "text-secondary": "#00d4b0",
        "text-placeholder": "#00b896",
        "accent-primary": "#ff00ff",
        "accent-secondary": "#e600e6",
        "border-color": "#404040",
        "danger-color": "#ff3366",
        "danger-hover-color": "#ff1a4d",
        "modal-bg": "rgba(0, 0, 0, 0.8)",
        "modal-content-bg": "#1a1a1a",
        "scrollbar-thumb": "#262626",
        "scrollbar-track": "#0f0f0f",
        "code-bg": "#1a1a1a"
    },
    "monochrome": {
        "bg-primary": "#ffffff",
        "bg-secondary": "#f5f5f5",
        "bg-tertiary": "#eeeeee",
        "bg-input": "#e0e0e0",
        "bg-hover": "#cccccc",
        "text-primary": "#000000",
        "text-secondary": "#333333",
        "text-placeholder": "#666666",
        "accent-primary": "#000000",
        "accent-secondary": "#4d4d4d",
        "border-color": "#bdbdbd",
        "danger-color": "#e53935",
        "danger-hover-color": "#d32f2f",
        "modal-bg": "rgba(255, 255, 255, 0.8)",
        "modal-content-bg": "#f5f5f5",
        "scrollbar-thumb": "#cccccc",
        "scrollbar-track": "#ffffff",
        "code-bg": "#eeeeee"
    },
    "solarized-light": {
        "bg-primary": "#fdf6e3",
        "bg-secondary": "#eee8d5",
        "bg-tertiary": "#e4d6ac",
        "bg-input": "#dfe6b8",
        "bg-hover": "#d6cfa5",
        "text-primary": "#657b83",
        "text-secondary": "#586e75",
        "text-placeholder": "#93a1a1",
        "accent-primary": "#268bd2",
        "accent-secondary": "#2aa198",
        "border-color": "#93a1a1",
        "danger-color": "#dc322f",
        "danger-hover-color": "#cb4b16",
        "modal-bg": "rgba(0, 0, 0, 0.7)",
        "modal-content-bg": "#eee8d5",
        "scrollbar-thumb": "#93a1a1",
        "scrollbar-track": "#fdf6e3",
        "code-bg": "#fdf6e3"
    },
    "solarized-dark": {
        "bg-primary": "#002b36",
        "bg-secondary": "#073642",
        "bg-tertiary": "#586e75",
        "bg-input": "#657b83",
        "bg-hover": "#839496",
        "text-primary": "#93a1a1",
        "text-secondary": "#839496",
        "text-placeholder": "#586e75",
        "accent-primary": "#268bd2",
        "accent-secondary": "#2aa198",
        "border-color": "#073642",
        "danger-color": "#dc322f",
        "danger-hover-color": "#cb4b16",
        "modal-bg": "rgba(0, 0, 0, 0.7)",
        "modal-content-bg": "#073642",
        "scrollbar-thumb": "#586e75",
        "scrollbar-track": "#002b36",
        "code-bg": "#002b36"
    },
    "neon": {
        "bg-primary": "#000000",
        "bg-secondary": "#0a0a0a",
        "bg-tertiary": "#141414",
        "bg-input": "#1e1e1e",
        "bg-hover": "#282828",
        "text-primary": "#39ff14",
        "text-secondary": "#2aff12",
        "text-placeholder": "#23e80f",
        "accent-primary": "#ff073a",
        "accent-secondary": "#e60033",
        "border-color": "#282828",
        "danger-color": "#ff3366",
        "danger-hover-color": "#ff1a4d",
        "modal-bg": "rgba(0, 0, 0, 0.9)",
        "modal-content-bg": "#141414",
        "scrollbar-thumb": "#1e1e1e",
        "scrollbar-track": "#000000",
        "code-bg": "#000000"
    },
    "forest": {
        "bg-primary": "#1b3a29",
        "bg-secondary": "#274c3c",
        "bg-tertiary": "#316f50",
        "bg-input": "#3a8e64",
        "bg-hover": "#45a078",
        "text-primary": "#e0f2e9",
        "text-secondary": "#b2d8c6",
        "text-placeholder": "#80cbb1",
        "accent-primary": "#5cb85c",
        "accent-secondary": "#4cae4c",
        "border-color": "#316f50",
        "danger-color": "#d9534f",
        "danger-hover-color": "#c9302c",
        "modal-bg": "rgba(0, 0, 0, 0.7)",
        "modal-content-bg": "#274c3c",
        "scrollbar-thumb": "#45a078",
        "scrollbar-track": "#1b3a29",
        "code-bg": "#1b3a29"
    }
}

for theme_name, variables in themes.items():
    file_path = os.path.join(output_dir, f"{theme_name}.css")
    with open(file_path, "w") as f:
        f.write(":root {\n")
        for var, value in variables.items():
            f.write(f"    --{var}: {value};\n")
        f.write("}\n")
    print(f"Generated {file_path}")
